# This file can update the JupyterHub Helm chart's default configuration values.
# #
# # For reference see the configuration reference and default values, but make
# # sure to refer to the Helm chart version of interest to you!
# #
# # Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# # Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# # Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# # Available chart versions: https://jupyterhub.github.io/helm-chart/
# #


singleuser:
  defaultUrl: "/lab"
  storage:
    extraVolumes:
      - name: cvmfs-fermilab
        persistentVolumeClaim:
          claimName: jupyterhub-cvmfs-fermilab
      - name: cvmfs-dune
        persistentVolumeClaim:
          claimName: jupyterhub-cvmfs-dune
      - name: cvmfs-larsoft
        persistentVolumeClaim:
          claimName: jupyterhub-cvmfs-larsoft

    extraVolumeMounts:
      - name: cvmfs-fermilab
        mountPath: /cvmfs/fermilab.opensciencegrid.org/
      - name: cvmfs-larsoft
        mountPath: /cvmfs/larsoft.opensciencegrid.org/
      - name: cvmfs-dune
        mountPath: /cvmfs/dune.opensciencegrid.org/

ingress:
  enabled: true
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

#  ingressClassName: nginx
#  pathType: Prefix
  hosts: 
    - website
proxy:
  service:
    type: ClusterIP

