apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs-dune-osgstorage
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvmfs-dune-osgstorage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cvmfs-dune-osgstorage
  local:
    path: /mnt/cvmfs-k8s/dune.osgstorage.org
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          -  fake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-dune-osgstorage
  namespace: cvmfs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: cvmfs-dune-osgstorage
