apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs-singularity
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvmfs-singularity
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cvmfs-singularity
  glusterfs:
    path: gluster/cvmfs-k8s/singularity.opensciencegrid.org
    endpoints: cvmfs-glusterfs
    endpointsNamespace: cvmfs
    readOnly: true
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          -  fake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-singularity
  namespace: cvmfs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: cvmfs-singularity
