- name: Check ansible version
  import_playbook: ansible_version.yml

- name: Ensure compatibility with old groups
  import_playbook: legacy_groups.yml

- name: Gather facts
  tags: always
  import_playbook: facts.yml


- hosts: all
  gather_facts: False
  #environment: "{{ proxy_disable_env }}"
  tasks:
     - name: Delete user
       user:
         name: axion
         state: absent
         remove: yes
         force: yes



